---
title: "Biostat 276 Homework 1"
author: "Zian ZHUANG"
output:
  pdf_document:
    toc: false
---

<!-- Setup -->
<style type="text/css">
body{ /* Normal  */
      font-size: 17px;
      font-family: "Times New Roman";
  }
h1,h2,h3,h4,h5,h6{
  font-family: "Times New Roman";
}
</style>
```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, cache.lazy = FALSE)
library(lars)
library(plotmo)
library(statmod)
library(reshape2)
library(MCMCpack)
library(tidyverse)
library(kableExtra)
```
<!-- Begin writing -->
## Bayesian Probit Regression

In R load the package (survival) and consider the analysis of the data-set (infert). Ignoring dependence due to matching, consider a Bayesian analysis for a logistic regression model relating case status to: age, parity, education, spontaneous and induced. More precisely, assume case status $y_i$ has density $y_i\sim _{ind}Bern(p_i),p_i=\Phi(X^{'}_i\beta)$, where
$\Phi(.)$ is the standard Gaussian cdf. Consider a prior $\beta\sim N(0,10^2(X^{'}X)^{-1})$. We are interested in $p(\beta|Y)$.

### (1) 

Describe and implement an adaptive Metropolis-Hastings algorithm designed to obtain a MC with stationary distribution $p(\beta|Y)$.

### (2) 

Describe and implement a data augmented (DA-MCMC ) strategy targeting $p(\beta|Y)$.

### (3)

Describe and implement a parameter expanded - data augmentation (PX-DA MCMC) algorithm targeting $p(\beta|Y)$.

### (4)

Assess mixing and convergence of the chains induced by the competing transition schemes implemented in 1,2 and 3. Comment on potential trade-offs involving: coding complexity, storage and cpu time.



